/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.util.logging.Level;
import java.util.logging.Logger;
import sistemasalud.Paciente;
import sistemasalud.Sistema;

/**
 *
 * @author andre
 */
public class CrearPaciente extends javax.swing.JFrame {

    /**
     * Creates new form CrearUsuario
     */
    Sistema system = new Sistema();
    public CrearPaciente() {
        initComponents();
        Idtxt.setEditable(false);
        Idtxt.setText("00001");
        
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexobtgr = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nombretxt = new javax.swing.JTextField();
        segundoNomtxt = new javax.swing.JTextField();
        apellido1txt = new javax.swing.JTextField();
        apellido2txt = new javax.swing.JTextField();
        fechaNacimientotxt = new com.toedter.calendar.JDateChooser();
        documentotxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TipoDocJcbox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        Idtxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        epstxt = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        MujerRdbt = new javax.swing.JRadioButton();
        HombreRdbt = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("CREAR PACIENTE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, 20));

        jLabel2.setText("*Tipo Documento:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, 20));

        jLabel3.setText("* Primer Apellido:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, 20));

        jLabel4.setText("* Segundo Apellido:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, 20));

        jLabel5.setText("Segundo Nombre:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel6.setText("Id:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        jLabel7.setText("* Sexo:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, 20));

        nombretxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombretxtActionPerformed(evt);
            }
        });
        getContentPane().add(nombretxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 190, -1));
        getContentPane().add(segundoNomtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 190, -1));
        getContentPane().add(apellido1txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 190, -1));
        getContentPane().add(apellido2txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 190, -1));

        fechaNacimientotxt.setToolTipText("");
        getContentPane().add(fechaNacimientotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 190, -1));
        getContentPane().add(documentotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 190, -1));

        jLabel8.setText("* Fecha Nacimiento:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, 20));

        jLabel9.setText("* Documento:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, 20));

        TipoDocJcbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Targeta Identidad", "Cedula de ciudadania", "Cedula de extranjeria", "Pasaporte" }));
        TipoDocJcbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoDocJcboxActionPerformed(evt);
            }
        });
        getContentPane().add(TipoDocJcbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 180, -1));

        jLabel10.setText("* Primer Nombre:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        Idtxt.setEnabled(false);
        Idtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdtxtActionPerformed(evt);
            }
        });
        getContentPane().add(Idtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 190, -1));

        jLabel11.setText("* Eps:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, 20));
        getContentPane().add(epstxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 190, -1));

        jToggleButton1.setText("Aceptar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, -1, -1));

        sexobtgr.add(MujerRdbt);
        MujerRdbt.setText("Mujer");
        MujerRdbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MujerRdbtActionPerformed(evt);
            }
        });
        getContentPane().add(MujerRdbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, -1, -1));

        sexobtgr.add(HombreRdbt);
        HombreRdbt.setText("Hombre");
        HombreRdbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HombreRdbtActionPerformed(evt);
            }
        });
        getContentPane().add(HombreRdbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombretxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombretxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombretxtActionPerformed

    private void TipoDocJcboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoDocJcboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoDocJcboxActionPerformed

    private void IdtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdtxtActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
       
        
        try {
           Paciente pas = new Paciente(Integer.parseInt(Idtxt.getText()),nombretxt.getText(),apellido1txt.getText(),apellido2txt.getText(),
                    (String) TipoDocJcbox.getSelectedItem(),
                    documentotxt.getText(),
                    fechaNacimientotxt.getCalendar(),
                    sexobtgr.getSelection().toString(),
                    system.RetornarEpsPorNombre(epstxt.getText()));
           
            if (!segundoNomtxt.getText().equals("")){ pas.setnombre2(segundoNomtxt.getText());}
            
        } catch (Exception ex) {
            Logger.getLogger(CrearPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
        
     
        
       
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void MujerRdbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MujerRdbtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MujerRdbtActionPerformed

    private void HombreRdbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HombreRdbtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HombreRdbtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearPaciente().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton HombreRdbt;
    private javax.swing.JTextField Idtxt;
    private javax.swing.JRadioButton MujerRdbt;
    private javax.swing.JComboBox<String> TipoDocJcbox;
    private javax.swing.JTextField apellido1txt;
    private javax.swing.JTextField apellido2txt;
    private javax.swing.JTextField documentotxt;
    private javax.swing.JTextField epstxt;
    private com.toedter.calendar.JDateChooser fechaNacimientotxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField nombretxt;
    private javax.swing.JTextField segundoNomtxt;
    private javax.swing.ButtonGroup sexobtgr;
    // End of variables declaration//GEN-END:variables
}
